function droptowerdata1 = importfile_droptower(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DROPTOWERDATA1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  DROPTOWERDATA1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  droptowerdata1 = importfile("C:\Users\Jason D. Bakos\Desktop\Dropbox\Jason\dropbear_lstm\drop_tower_data.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Jun-2021 09:29:16

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "test1", "test2", "test3", "test4", "test5"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
droptowerdata1 = readtable(filename, opts);

end